modLoader = "javafml"
loaderVersion = "[24,)"
license = "https://github.com/WhoCraft/Weeping-Angels/blob/1.16/LICENSE"
issueTrackerURL = "https://github.com/WhoCraft/Weeping-Angels/issues"
[[mods]]
displayURL = "https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod"
logoFile = "logo.png"
credits = "Suff, 50ap5ud5, Ed, Violet, Rolf, Nictogen, Lukas, ShadowBolt, ItzAngela, DocArcane, Dhi_awesome, ConnorDawn"
authors = "Suff99, 50ap5ud5"
itemIcon = "weeping_angels:timey_wimey_detector"
modId = "weeping_angels"
version = "${version}"
displayName = "Weeping Angels"
updateJSONURL = "https://raw.githubusercontent.com/WhoCraft/Weeping-Angels/1.16/update.json" #optional
description = '''
Mod that adds the terrifying Weeping Angel creatures to Minecraft || Originally made for ModJam 5'''
[[dependencies.weeping_angels]]
modId = "forge"
mandatory = true
versionRange = "[28,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.weeping_angels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3, ]"
ordering = "NONE"
side = "BOTH"